<?php namespace Taxamo;
/**
 *  Copyright 2014-2018 Taxamo
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Additional_interactions {

  static $swaggerTypes = array(
      'requested' => 'bool',
      'captcha' => 'captcha',
      'interaction_kind' => 'string',
      'interaction_result' => 'string',
      'interaction_result_message' => 'string',
      'region_key' => 'string',
      'required' => 'bool',
      'interaction_key' => 'string',
      'interaction_prompt_message' => 'string',
      'force_valid' => 'bool'

    );

  /**
  * Should Taxamo trigger this interaction (e.g. request captcha image) if possible. Please note this will increase request time as we have to reach out to an external resources.
  */
  public $requested; // bool
  /**
  * Captcha-specific information
  */
  public $captcha; // captcha
  /**
  * Kind of the interaction, e.g. b2b-captcha
  */
  public $interaction_kind; // string
  /**
  * Interaction result. For b2b-captcha it will be valid|invalid|error|expired.
  */
  public $interaction_result; // string
  /**
  * Interaction result message, useful in case there is an error.
  */
  public $interaction_result_message; // string
  /**
  * Region key for this interaction, e.g. IN or EU.
  */
  public $region_key; // string
  /**
  * If the interaction triggered validation fails, return validation error. This is useful when getting to store the transaction with successful b2b validation, for later reference via original_transaction_key.
  */
  public $required; // bool
  /**
  * Key regarding the interaction, e.g. india-b2b-captcha
  */
  public $interaction_key; // string
  /**
  * Message that can be presented in the UI requesting for the interaction.
  */
  public $interaction_prompt_message; // 
  /**
  * Regardless of other flags in this interaction, treat the validation as successful. This for example can be used to display the prices without tax in case of captcha-based B2B validation - when we don't want to show multiple captchas for every tax calculation.
  */
  public $force_valid; // bool
  }

