<?php namespace Taxamo;
/**
 *  Copyright 2014-2018 Taxamo
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Captcha {

  static $swaggerTypes = array(
      'riddle_key' => 'string',
      'resolution_mode' => 'string',
      'resolution_id' => 'string',
      'image_url' => 'string',
      'image_base64' => 'string',
      'solution' => 'string'

    );

  /**
  * Captcha riddle key, has to be sent back with Captcha solution.
  */
  public $riddle_key; // string
  /**
  * 
  */
  public $resolution_mode; // string
  /**
  * 
  */
  public $resolution_id; // string
  /**
  * Captcha image url.
  */
  public $image_url; // string
  /**
  * Captcha image as base64. Used where it is not possible to direct the customer to captcha image URL. To display it in a browser, for example you can prefix it with &quot;data:image/png;base64, &quot; and use this as an image URL.
  */
  public $image_base64; // string
  /**
  * Captcha solution provided by the human.
  */
  public $solution; // string
  }

