<?php namespace Taxamo;
/**
 *  Copyright 2014 Taxamo, Ltd.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class GetDomesticSummaryReportOut {

  static $swaggerTypes = array(
      'end_date' => 'string',
      'domestic_refunds_amount' => 'number',
      'currency_code' => 'string',
      'global_refunds_tax_amount' => 'number',
      'domestic_refunds_tax_amount' => 'number',
      'eu_tax_deducted_refunds' => 'number',
      'global_sales_amount' => 'number',
      'global_refunds_amount' => 'number',
      'global_sales_tax_amount' => 'number',
      'eu_tax_deducted_sales' => 'number',
      'start_date' => 'string',
      'domestic_tax_amount' => 'number',
      'domestic_sales_amount' => 'number'

    );

  /**
  * Period end date in yyyy-MM-dd'T'hh:mm:ss'Z' format.
  */
  public $end_date; // string
  /**
  * Domestic sales refunds amount.
  */
  public $domestic_refunds_amount; // number
  /**
  * Three-letter ISO currency code.
  */
  public $currency_code; // string
  /**
  * Global sales refunds amount. This includes refunds from domestic country too.
  */
  public $global_refunds_tax_amount; // number
  /**
  * Domestic sales refunds tax amout.
  */
  public $domestic_refunds_tax_amount; // number
  /**
  * EU deducted tax sales.
  */
  public $eu_tax_deducted_refunds; // number
  /**
  * Global sales amount. This includes sales from domestic country too.
  */
  public $global_sales_amount; // number
  /**
  * Global sales refunds amount. This includes refunds from domestic country too.
  */
  public $global_refunds_amount; // number
  /**
  * Global sales amount. This includes sales from domestic country too.
  */
  public $global_sales_tax_amount; // number
  /**
  * EU deducted tax sales.
  */
  public $eu_tax_deducted_sales; // number
  /**
  * Period start date in yyyy-MM-dd'T'hh:mm:ss'Z' format.
  */
  public $start_date; // string
  /**
  * Domestic sales tax amout.
  */
  public $domestic_tax_amount; // number
  /**
  * Domestic sales amount.
  */
  public $domestic_sales_amount; // number
  }

