<?php namespace Taxamo;
/**
 *  Copyright 2014 Taxamo, Ltd.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Refunds {

  static $swaggerTypes = array(
      'refund_note_url' => 'string',
      'refund_note_number' => 'string',
      'line_key' => 'string',
      'refund_timestamp' => 'string',
      'amount' => 'number',
      'informative' => 'bool',
      'tax_amount' => 'number',
      'tax_rate' => 'number',
      'total_amount' => 'number',
      'refund_reason' => 'string'

    );

  /**
  * Refund note image url.
  */
  public $refund_note_url; // string
  /**
  * Sequential refund note number.
  */
  public $refund_note_number; // string
  /**
  * Line identifier. If neither line key or custom id is provided, the refund amount will be assigned to lines in order.
  */
  public $line_key; // string
  /**
  * Refund timestamp in UTC timezone.
  */
  public $refund_timestamp; // string
  /**
  * Amount, excluding tax, that was refunded.
  */
  public $amount; // number
  /**
  * Was this refund applied to an informative line?
  */
  public $informative; // bool
  /**
  * Calculated tax amount, that was refunded.
  */
  public $tax_amount; // number
  /**
  * Tax rate for the line that was used for the refund calculation.
  */
  public $tax_rate; // number
  /**
  * Total amount, including tax, that was refunded.
  */
  public $total_amount; // number
  /**
  * Refund reason, displayed on the credit note.
  */
  public $refund_reason; // string
  }

