<?php
/**
 *  Copyright 2014 Taxamo, Ltd.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Settlement_daily_stats_schema {

  static $swaggerTypes = array(
      'b2c' => 'integer',
      'untaxed' => 'integer',
      'eu_taxed' => 'integer',
      'eu_b2b' => 'integer',
      'count' => 'integer',
      'eu_total' => 'integer',
      'day_raw' => 'string',
      'b2b' => 'integer',
      'day' => 'string'

    );

  /**
  * B2C transaction count.
  */
  public $b2c; // integer
  /**
  * Untaxed transaction count.
  */
  public $untaxed; // integer
  /**
  * Total EU Taxed transaction count.
  */
  public $eu_taxed; // integer
  /**
  * Total EU B2B transaction count.
  */
  public $eu_b2b; // integer
  /**
  * Total transaction count.
  */
  public $count; // integer
  /**
  * Total EU transaction count.
  */
  public $eu_total; // integer
  /**
  * Date for stats in yyyy-MM-dd'T'hh:mm:ss'Z' format.
  */
  public $day_raw; // string
  /**
  * B2B transaction count.
  */
  public $b2b; // integer
  /**
  * Date for stats in yyyy-MM-dd format.
  */
  public $day; // string
  }

