<?php namespace Taxamo;
/**
 *  Copyright 2014 Taxamo, Ltd.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Us_tax_exemption_certificate_details_schema {

  static $swaggerTypes = array(
      'single_purchase_order_identifier' => 'string',
      'purchaser_business_type' => 'string',
      'purchaser_exemption_reason_value' => 'string',
      'purchaser_state' => 'string',
      'purchaser_zip' => 'string',
      'purchaser_city' => 'string',
      'purchaser_last_name' => 'string',
      'purchaser_exemption_reason' => 'string',
      'single_purchase' => 'bool',
      'purchaser_tax_id' => 'us_tax_id',
      'purchaser_address2' => 'string',
      'purchaser_address1' => 'string',
      'purchaser_business_type_other_value' => 'string',
      'purchaser_first_name' => 'string',
      'exempt_states' => 'array[us_tax_exempt_state]',
      'purchaser_title' => 'string'

    );

  /**
  * Purchase/order identifier for single purchase.
  */
  public $single_purchase_order_identifier; // string
  /**
  * Purchaser business type.
  */
  public $purchaser_business_type; // string
  /**
  * The value of exemption reason.
  */
  public $purchaser_exemption_reason_value; // string
  /**
  * Purchaser's state.
  */
  public $purchaser_state; // string
  /**
  * Purchaser's zip code.
  */
  public $purchaser_zip; // string
  /**
  * Purchaser's city.
  */
  public $purchaser_city; // string
  /**
  * Purchaser's last name.
  */
  public $purchaser_last_name; // string
  /**
  * The reason for exemption reason.
  */
  public $purchaser_exemption_reason; // string
  /**
  * Set to true if this certificate is valid for single purchase only.
  */
  public $single_purchase; // bool
  /**
  * Purchaser's TAX ID.
  */
  public $purchaser_tax_id; // us_tax_id
  /**
  * Purchaser's second address line.
  */
  public $purchaser_address2; // string
  /**
  * Purchaser's first address line.
  */
  public $purchaser_address1; // string
  /**
  * If business type is other, a short description must be provided.
  */
  public $purchaser_business_type_other_value; // string
  /**
  * Purchaser's first name.
  */
  public $purchaser_first_name; // string
  /**
  * List of states where the certificate is valid.
  */
  public $exempt_states; // array[us_tax_exempt_state]
  /**
  * Purchaser's title.
  */
  public $purchaser_title; // string
  }

