<?php namespace Taxamo;
/**
 *  Copyright 2014 Taxamo, Ltd.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Us_tax_id {

  static $swaggerTypes = array(
      'tax_id_type' => 'string',
      'tax_id' => 'string',
      'state_of_issue' => 'string'

    );

  /**
  * Tax id type.
  */
  public $tax_id_type; // string
  /**
  * Tax ID
  */
  public $tax_id; // string
  /**
  * State of issue
  */
  public $state_of_issue; // string
  }

